---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: ["-c", "./.yamllint.yml"]
        stages: [commit]
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        description: "Check the profile for Ansible best practices."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/ansible-lint.sh
        files: "^.+\\.(yaml|yml)$"
        language: system
        pass_filenames: false
        stages: [commit]
      - id: shell-fmt
        name: shell-fmt
        description: "Format the project's shell scripts."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/shell-fmt.sh
        exclude: "^\\.cicd-tools/ci/.+$"
        files: "^.+\\.(bash|sh)$"
        language: system
        pass_filenames: true
        stages: [commit]
      - id: shell-lint
        name: shell-lint
        description: "Lint the project's shell scripts."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/shell-lint.sh
        exclude: "^\\.cicd-tools/ci/.+$"
        files: "^.+\\.(bash|sh)$"
        language: system
        pass_filenames: true
        stages: [commit]
