---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-jsonschema
        name: check-cookiecutter-schema
        files: "^\\.cookiecutter/cookiecutter\\.json$"
        args: ["--schemafile", ".cicd-tools/boxes/bootstrap/schemas/cookiecutter.json"]
        stages: [commit]
      - id: check-jsonschema
        name: check-github-workflow-push-schema
        files: "^\\.github/config/workflows/workflow-push.json$"
        args: ["--schemafile", ".github/config/schemas/workflows/workflow-push.json"]
        stages: [commit]
      - id: check-jsonschema
        name: check-github-workflow-publish-to-galaxy-schema
        files: "^\\.github/config/workflows/workflow-publish-to-galaxy.json$"
        args: ["--schemafile", ".github/config/schemas/workflows/workflow-publish-to-galaxy.json"]
        stages: [commit]
      - id: check-metaschema
        name: check-github-workflow-metaschemas
        files: "^\\.github/config/schemas/.*\\.json$"
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: ["-c", "./.yamllint.yml"]
        stages: [commit]
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        description: "Check the profile for Ansible best practices."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/ansible-lint.sh
        files: "^.+\\.(yaml|yml)$"
        language: system
        pass_filenames: false
        stages: [commit]
      - id: shell-fmt
        name: shell-fmt
        description: "Format the project's shell scripts."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/shell-fmt.sh
        exclude: "^\\.cicd-tools/boxes/.+$|^\\.github/deactivated/.+$"
        files: "^.+\\.(bash|sh)$"
        language: system
        pass_filenames: true
        stages: [commit]
      - id: shell-lint
        name: shell-lint
        description: "Lint the project's shell scripts."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/shell-lint.sh
        exclude: "^\\.cicd-tools/boxes/.+$|^\\.github/deactivated/.+$"
        files: "^.+\\.(bash|sh)$"
        language: system
        pass_filenames: true
        stages: [commit]
