---
- name: Converge
  hosts: all
  connection: local
  tasks:
    - name: Load Scenario Variables
      include_vars: vars/main.yml
    - name: "Include niall_byrne.flower_generator"
      ansible.builtin.include_role:
        name: "niall_byrne.flower_generator"
